spring:
  profiles:
    active: blue
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  env: blue

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
  serverAddress: localhost
serverName: local_server
file:
  upload:
    dir: ./images/

---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8080
  serverAddress: ${AWS_PUBLIC_IP}
serverName: blue_server
file:
  upload:
    dir: /var/app/images/

---
spring:
  config:
    activate:
      on-profile: green
server:
  port: 8081
  serverAddress: ${AWS_PUBLIC_IP}
serverName: green_server
file:
  upload:
    dir: /var/app/images/

---

spring:
  application:
    name: team3-be
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kakao:
    api-key: ${KAKAO_API_KEY}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cors:
  allowed_origin: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    org.springframework: INFO

openai:
  api-key: ${OPENAI_API_KEY}

#헬스체크
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: likelion.controller
  paths-to-match: /api/**